INSERT INTO USER (FIRST_name,last_name,nick_name,email,password,average_rating,review_number_counter) values('alkin','sen','sena','alkin.sen@monitise.com','Passw0rd',0,0);
INSERT INTO USER (FIRST_name,last_name,nick_name,email,password,average_rating,review_number_counter) values('enis','simsar','simsare','enis.simssar@monitise.com','Passw0rd',0,0);
INSERT INTO USER (FIRST_name, last_name, nick_name, email, PASSWORD,average_rating,review_number_counter) VALUES ('yalin', 'popstar', 'yapops', 'yalin.pops@muzique.com', '123456',0,0);
INSERT INTO USER (FIRST_name, last_name, nick_name, email, PASSWORD,average_rating,review_number_counter) VALUES ('burak', 'yilmaz', 'byilmaz', 'burak.yilmaz@monitise.com', 'cimbom',0,0);
INSERT INTO USER (FIRST_name, last_name, nick_name, email, PASSWORD,average_rating,review_number_counter) VALUES ('serdar', 'ortac', 'sortac', 'serdar.ortac@monitise.com', 'giybet',0,0);
INSERT INTO COUPON (user_id, title, description, accepts_cash_payment, accepts_online_payment, cold_vote_counter, hot_vote_counter, is_active) VALUES (2, 'beles konser', 'harika bir firsat', TRUE, TRUE, 0, 0, TRUE);
INSERT INTO COUPON (user_id, title, description, accepts_cash_payment, accepts_online_payment, cold_vote_counter, hot_vote_counter, is_active) VALUES (3, 'beles koltuk', 'belese otur', TRUE, TRUE, 0, 0, TRUE);
INSERT INTO COUPON (user_id, title, description, accepts_cash_payment, accepts_online_payment, cold_vote_counter, hot_vote_counter, is_active) VALUES (4, 'ucuz ayakkabı', 'yuru bee', TRUE, TRUE, 0, 0, TRUE);
INSERT INTO COUPON (user_id, title, description, accepts_cash_payment, accepts_online_payment, cold_vote_counter, hot_vote_counter, is_active) VALUES (2, 'maliyetine kullanılmış çamaşır', 'az kullanılmış', TRUE, TRUE, 0, 0, TRUE);
INSERT INTO DEAL (user_id, title, description, cold_vote_counter, hot_vote_counter) VALUES (1, 'nusrette %20', 'at etinden geçerli sadece', 0, 0);
INSERT INTO DEAL (user_id, title, description, cold_vote_counter, hot_vote_counter) VALUES (2, 'nusrette %50', 'sadece suda geçerli', 0, 0);
INSERT INTO DEAL (user_id, title, description, cold_vote_counter, hot_vote_counter) VALUES (2, 'nusrette +%10', 'bu dealla %10 fazla ödeyip bahşiş bırakmasanda olur', 0, 0);
INSERT INTO DEAL (user_id, title, description, cold_vote_counter, hot_vote_counter) VALUES (5, 'nusret -%0', 'normal parayı veriyon', 0, 0);
INSERT INTO REFERENCE (comment,rating,writer_nickname,user_id, date_of_creation) VALUES ('terasta çok az vakit geçiriyor', 3, 'sena', 2, CURRENT_TIMESTAMP );
INSERT INTO REFERENCE (comment,rating,writer_nickname,user_id, date_of_creation) VALUES ('mutfakta çok vakit geçiriyor', 2, 'android_head', 2, CURRENT_TIMESTAMP );
INSERT INTO REFERENCE (comment,rating,writer_nickname,user_id, date_of_creation) VALUES ('iyi çalışıyor', 5, 'ailerle', 2, CURRENT_TIMESTAMP );
INSERT INTO user_interest (user_id,interest_set) VALUES (2,'CLOTHING');
INSERT INTO user_interest (user_id,interest_set) VALUES (1,'ELECTRONICS');
INSERT INTO user_interest (user_id,interest_set) VALUES (1,'FOOD');
INSERT INTO deal_categories (deal_id,categories) VALUES (1,'FOOD');
INSERT INTO deal_categories (deal_id,categories) VALUES (2,'FOOD');
INSERT INTO deal_categories (deal_id,categories) VALUES (3,'FOOD');
INSERT INTO deal_categories (deal_id,categories) VALUES (4,'FOOD');